name: grumphp-check
run-name: Running GrumPHP checks
on: [push]
jobs:
  run-grumphp:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install composer and dependencies
        uses: php-actions/composer@v6

      - name: Run GrumPHP checks
        run: vendor/bin/grumphp run